debug = false                                                                                                                       
logLevel = "INFO"                                                                                                                   
defaultEntryPoints = [ "http", "https"]                                                                                             
                                                                                                                                    
[web]                                                                                                                               
address = ":8080"
